trigger:
  batch: true
  tags:
    include:
      - '2.*'
  branches:
    include:
      - develop
  paths:
    include:
      - '*'
      - apps/innovations
    exclude:
      - apps

name: FA_Innovations_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:r)

pool:
  vmImage: ubuntu-latest

extends:
  template: ../../../.pipelines/build-function-app.yml
  parameters:
      appName: innovations
