trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    include:
      - '*'
      - apps/users
    exclude:
      - apps

variables:
  appName: users

name: FA_Users_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

pool:
  vmImage: ubuntu-latest

extends:
  template: ../../../.pipelines/build-function-app.yml
  parameters:
      users: innovations
