trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    include:
      - '*'
      - apps/notifications
    exclude:
      - apps

name: FA_Notifications_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

pool:
  vmImage: ubuntu-latest

extends:
  template: ../../../.pipelines/build-function-app.yml
  parameters:
      appName: notifications
      hasApim: false
