openapi: "3.0.3"
info:
  title: "Innovation Service - Innovations API"
  version: "1.0.0"
servers:
  - url: 'https://nhse-${ENV}-innovation-service-innovation-functions.azurewebsites.net/api'

paths:
  "/v1":
    post:
      tags:
        - "v1"
        - "Innovations"
      description: "Creates an innovation"
      operationId: "v1-innovation-create"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"

  "/v1/transfers":
    get:
      tags:
        - "v1"
        - "Transfers"
      description: "Retrieves innovation transfer list"
      operationId: "v1-innovation-transfer-list"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    post:
      tags:
        - "v1"
        - "Transfers"
      description: "Creates a transfer"
      operationId: "v1-innovation-transfer-create"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"

  "/v1/transfers/{transferId}":
    get:
      tags:
        - "v1"
        - "Transfers"
      description: "Retrieves the innovation transfer information"
      operationId: "v1-innovation-transfer-info"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    put:
      tags:
        - "v1"
        - "Transfers"
      description: "Updates innovation transfer information"
      operationId: "v1-innovation-transfer-update"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Ok"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
