openapi: "3.0.3"
info:
  title: "Innovation Service - Innovations API"
  version: "1.0.0"
servers:
  - url: 'https://nhse-${ENV}-innovation-service-innovation-functions.azurewebsites.net/api'

paths:
  "/v1":
    get:
      tags:
        - "[v1] Innovations"
      description: "Get innovations list "
      operationId: "v1-innovations-list"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
    post:
      tags:
        - "[v1] Innovations"
      description: "Creates an innovation"
      operationId: "v1-innovation-create"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"

  "/v1/overdue-assessments":
    get:
      tags:
        - "[v1] Innovations"
      description: "Get assessment overdue innovations"
      operationId: "v1-innovations-list"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"

  "/v1/transfers":
    get:
      tags:
        - "[v1] Transfers"
      description: "Retrieves innovation transfer list"
      operationId: "v1-innovation-transfer-list"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    post:
      tags:
        - "[v1] Transfers"
      description: "Creates a transfer"
      operationId: "v1-innovation-transfer-create"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"

  "/v1/transfers/{transferId}":
    get:
      tags:
        - "[v1] Transfers"
      description: "Retrieves the innovation transfer information"
      operationId: "v1-innovation-transfer-info"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
    patch:
      tags:
        - "[v1] Transfers"
      description: "Updates innovation transfer information"
      operationId: "v1-innovation-transfer-update"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Ok"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"

  "/v1/transfers/{transferId}/check":
    get:
      tags:
        - "[v1] Transfers"
      description: "Check user innovation transfer information"
      operationId: "v1-innovation-transfer-check"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Ok"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"

  "/v1/{innovationId}/sections/{sectionId}":
    get:
      tags:
        - "[v1] Sections"
      description: "Get an innovation section info."
      operationId: "v1-innovation-section-info"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
        - name: sectionId
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"

  "/v1/{innovationId}/sections":
    get:
      tags:
        - "[v1] Sections"
      description: "Get an innovation sections list."
      operationId: "v1-innovation-sections-list"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"

  "/v1/{innovationId}/sections/{sectionKey}":
    put:
      tags:
        - "[v1] Sections"
      description: "Updates an innovation section"
      operationId: "v1-innovation-section-update"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
        - name: sectionKey
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
    patch:
      tags:
        - "[v1] Sections"
      description: "Submits an innovation section"
      operationId: "v1-innovation-section-submit"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
        - name: sectionKey
          in: path
          schema:
            type: string
          required: true
      responses:
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
          
  "/v1/{innovationId}/submit":
    patch:
      tags:
        - "[v1] Innovations"
      description: "Submit innovation for assessment"
      operationId: "v1-innovation-submit"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"

  "/v1/{innovationId}/assessments":
    post:
      tags:
        - "[v1] Innovations"
      description: "Initiate innovation assessment"
      operationId: "v1-innovation-assessment-create"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"

  "/v1/{innovationId}/assessments/{assessmentId}":
    get:
      tags:
        - "[v1] Innovations"
      description: "get innovation assessment info"
      operationId: "v1-innovation-assessment-info"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
        - name: assessmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
    post:
      tags:
        - "[v1] Innovations"
      description: "update innovation assessment"
      operationId: "v1-innovation-assessment-update"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          required: true
        - name: innovationId
          in: path
          required: true
          schema:
            type: string
        - name: assessmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"