export enum ActivityTypeEnum {
  INNOVATION_MANAGEMENT = 'INNOVATION_MANAGEMENT',
  INNOVATION_RECORD = 'INNOVATION_RECORD',
  NEEDS_ASSESSMENT = 'NEEDS_ASSESSMENT',
  SUPPORT = 'SUPPORT',
  COMMENTS = 'COMMENTS',
  ACTIONS = 'ACTIONS',
  THREADS = 'THREADS',
}

export enum ActivityEnum {
  INNOVATION_CREATION = 'INNOVATION_CREATION',
  OWNERSHIP_TRANSFER = 'OWNERSHIP_TRANSFER',
  SHARING_PREFERENCES_UPDATE = 'SHARING_PREFERENCES_UPDATE',
  SECTION_DRAFT_UPDATE = 'SECTION_DRAFT_UPDATE',
  SECTION_SUBMISSION = 'SECTION_SUBMISSION',
  INNOVATION_SUBMISSION = 'INNOVATION_SUBMISSION',
  NEEDS_ASSESSMENT_START = 'NEEDS_ASSESSMENT_START',
  NEEDS_ASSESSMENT_COMPLETED = 'NEEDS_ASSESSMENT_COMPLETED',
  NEEDS_ASSESSMENT_EDITED = 'NEEDS_ASSESSMENT_EDITED',
  ORGANISATION_SUGGESTION = 'ORGANISATION_SUGGESTION',
  SUPPORT_STATUS_UPDATE = 'SUPPORT_STATUS_UPDATE',
  COMMENT_CREATION = 'COMMENT_CREATION',
  ACTION_CREATION = 'ACTION_CREATION',
  ACTION_STATUS_SUBMITTED_UPDATE = 'ACTION_STATUS_SUBMITTED_UPDATE',
  ACTION_STATUS_DECLINED_UPDATE = 'ACTION_STATUS_DECLINED_UPDATE',
  ACTION_STATUS_COMPLETED_UPDATE = 'ACTION_STATUS_COMPLETED_UPDATE',
  ACTION_STATUS_REQUESTED_UPDATE = 'ACTION_STATUS_REQUESTED_UPDATE',
  ACTION_STATUS_CANCELLED_UPDATE = 'ACTION_STATUS_CANCELLED_UPDATE',
  THREAD_CREATION = 'THREAD_CREATION',
  THREAD_MESSAGE_CREATION = 'THREAD_MESSAGE_CREATION',
  NEEDS_ASSESSMENT_REASSESSMENT_REQUESTED = 'NEEDS_ASSESSMENT_REASSESSMENT_REQUESTED',
  INNOVATION_PAUSE = 'INNOVATION_PAUSE'
}
