export enum YesOrNoCatalogueEnum {
  YES = 'YES',
  NO = 'NO'
}

export enum YesPartiallyNoCatalogueEnum {
  YES = 'YES',
  PARTIALLY = 'PARTIALLY',
  NO = 'NO'
}

export enum YesNoNotRelevantCatalogueEnum {
  YES = 'YES',
  NO = 'NO',
  NOT_RELEVANT = 'NOT_RELEVANT'
}

export enum CarePathwayCatalogueEnum {
  ONLY_OPTION = 'ONLY_OPTION',
  BETTER_OPTION = 'BETTER_OPTION',
  EQUIVALENT_OPTION = 'EQUIVALENT_OPTION',
  FIT_LESS_COSTS = 'FIT_LESS_COSTS',
  NO_KNOWLEDGE = 'NO_KNOWLEDGE'
}

export enum PatientRangeCatalogueEnum {
  UP_10000 = 'UP_10000',
  BETWEEN_10000_500000 = 'BETWEEN_10000_500000',
  MORE_THAN_500000 = 'MORE_THAN_500000',
  NOT_SURE = 'NOT_SURE',
  NOT_RELEVANT = 'NOT_RELEVANT'
}

export enum CostComparisonCatalogueEnum {
  CHEAPER = 'CHEAPER',
  COSTS_MORE_WITH_SAVINGS = 'COSTS_MORE_WITH_SAVINGS',
  COSTS_MORE = 'COSTS_MORE',
  NOT_SURE = 'NOT_SURE'
}

export enum EvidenceTypeCatalogueEnum {
  CLINICAL = 'CLINICAL',
  ECONOMIC = 'ECONOMIC',
  OTHER = 'OTHER'
}

export enum ClinicalEvidenceTypeCatalogueEnum {
  DATA_PUBLISHED = 'DATA_PUBLISHED',
  NON_RANDOMISED_COMPARATIVE_DATA = 'NON_RANDOMISED_COMPARATIVE_DATA',
  NON_RANDOMISED_NON_COMPARATIVE_DATA = 'NON_RANDOMISED_NON_COMPARATIVE_DATA',
  CONFERENCE = 'CONFERENCE',
  RANDOMISED_CONTROLLED_TRIAL = 'RANDOMISED_CONTROLLED_TRIAL',
  UNPUBLISHED_DATA = 'UNPUBLISHED_DATA',
  OTHER = 'OTHER'
}

export enum StandardMetCatalogueEnum {
  YES = 'YES',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_YET = 'NOT_YET'
}

export enum MainPurposeCatalogueEnum {
  PREVENT_CONDITION = 'PREVENT_CONDITION',
  PREDICT_CONDITION = 'PREDICT_CONDITION',
  DIAGNOSE_CONDITION = 'DIAGNOSE_CONDITION',
  MONITOR_CONDITION = 'MONITOR_CONDITION',
  PROVIDE_TREATMENT = 'PROVIDE_TREATMENT',
  MANAGE_CONDITION = 'MANAGE_CONDITION',
  ENABLING_CARE = 'ENABLING_CARE'
}

export enum HasProblemTackleKnowledgeCatalogueEnum {
  YES = 'YES',
  NOT_YET = 'NOT_YET',
  NOT_SURE = 'NOT_SURE'
}

export enum HasBenefitsCatalogueEnum {
  YES = 'YES',
  NOT_YET = 'NOT_YET',
  NOT_SURE = 'NOT_SURE'
}

export enum HasEvidenceCatalogueEnum {
  YES = 'YES',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_YET = 'NOT_YET'
}

export enum HasMarketResearchCatalogueEnum {
  YES = 'YES',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_YET = 'NOT_YET'
}

export enum HasPatentsCatalogueEnum {
  HAS_AT_LEAST_ONE = 'HAS_AT_LEAST_ONE',
  APPLIED_AT_LEAST_ONE = 'APPLIED_AT_LEAST_ONE',
  HAS_NONE = 'HAS_NONE'
}

export enum HasRegulationKnowledegeCatalogueEnum {
  YES_ALL = 'YES_ALL',
  YES_SOME = 'YES_SOME',
  NO = 'NO',
  NOT_RELEVANT = 'NOT_RELEVANT'
}

export enum InnovationPathwayKnowledgeCatalogueEnum {
  PATHWAY_EXISTS_AND_CHANGED = 'PATHWAY_EXISTS_AND_CHANGED',
  PATHWAY_EXISTS_AND_FITS = 'PATHWAY_EXISTS_AND_FITS',
  NO_PATHWAY = 'NO_PATHWAY'
}

export enum HasTestsCatalogueEnum {
  YES = 'YES',
  IN_PROCESS = 'IN_PROCESS',
  NOT_YET = 'NOT_YET'
}

export enum HasKnowledgeCatalogueEnum {
  DETAILED_ESTIMATE = 'DETAILED_ESTIMATE',
  ROUGH_IDEA = 'ROUGH_IDEA',
  NO = 'NO'
}

export enum HasFundingCatalogueEnum {
  YES = 'YES',
  NO = 'NO',
  NOT_RELEVANT = 'NOT_RELEVANT'
}

export enum HasResourcesToScaleCatalogueEnum {
  YES = 'YES',
  NO = 'NO',
  NOT_SURE = 'NOT_SURE'
}

export enum InnovationCategoryCatalogueEnum {
  MEDICAL_DEVICE = 'MEDICAL_DEVICE',
  PHARMACEUTICAL = 'PHARMACEUTICAL',
  DIGITAL = 'DIGITAL',
  AI = 'AI',
  EDUCATION = 'EDUCATION',
  PPE = 'PPE',
  OTHER = 'OTHER'
}

export enum InnovationAreaCatalogueEnum {
  WORKFORCE = 'WORKFORCE',
  ECONOMIC_GROWTH = 'ECONOMIC_GROWTH',
  EVIDENCE_GENERATION = 'EVIDENCE_GENERATION',
  TRANSFORMED_OUT_OF_HOSPITAL_CARE = 'TRANSFORMED_OUT_OF_HOSPITAL_CARE',
  REDUCIND_PRESSURE_EMERGENCY_HOSPITAL_SERVICES = 'REDUCIND_PRESSURE_EMERGENCY_HOSPITAL_SERVICES',
  CONTROL_OVER_THEIR_OWN_HEALTH = 'CONTROL_OVER_THEIR_OWN_HEALTH',
  DIGITALLY_ENABLING_PRIMARY_CARE = 'DIGITALLY_ENABLING_PRIMARY_CARE',
  CANCER = 'CANCER',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  CHILDREN_AND_YOUNG_PEOPLE = 'CHILDREN_AND_YOUNG_PEOPLE',
  LEARNING_DISABILITIES_AND_AUTISM = 'LEARNING_DISABILITIES_AND_AUTISM',
  CARDIOVASCULAR_DISEASE = 'CARDIOVASCULAR_DISEASE',
  STROKE_CARE = 'STROKE_CARE',
  DIABETES = 'DIABETES',
  RESPIRATORY = 'RESPIRATORY',
  RESEARCH_INNOVATION_DRIVE_FUTURE_OUTCOMES = 'RESEARCH_INNOVATION_DRIVE_FUTURE_OUTCOMES',
  GENOMICS = 'GENOMICS',
  WIDER_SOCIAL_IMPACT = 'WIDER_SOCIAL_IMPACT',
  REDUCING_VARIATION_ACROSS_HEALTH_SYSTEM = 'REDUCING_VARIATION_ACROSS_HEALTH_SYSTEM',
  FINANCIAL_PLANNING_ASSUMPTIONS = 'FINANCIAL_PLANNING_ASSUMPTIONS',
  COVID_19 = 'COVID_19',
  DATA_ANALYTICS_AND_RESEARCH = 'DATA_ANALYTICS_AND_RESEARCH',
  IMPROVING_SYSTEM_FLOW = 'IMPROVING_SYSTEM_FLOW',
  INDEPENDENCE_AND_PREVENTION = 'INDEPENDENCE_AND_PREVENTION',
  OPERATIONAL_EXCELLENCE = 'OPERATIONAL_EXCELLENCE',
  PATIENT_ACTIVATION_AND_SELF_CARE = 'PATIENT_ACTIVATION_AND_SELF_CARE',
  PATIENT_SAFETY = 'PATIENT_SAFETY',
  GREATER_SUPPORT_AND_RESOURCE_PRIMARY_CARE = 'GREATER_SUPPORT_AND_RESOURCE_PRIMARY_CARE'
}

/**
 * @deprecated enum.
 * This enum is not being used anymore.
 */
export enum InnovationClinicalAreaCatalogueEnum {
  ACUTE = 'ACUTE',
  AGEING = 'AGEING',
  CANCER = 'CANCER',
  CARDIO_ENDOCRINE_METABOLIC = 'CARDIO_ENDOCRINE_METABOLIC',
  CHILDREN_AND_YOUNG = 'CHILDREN_AND_YOUNG',
  DISEASE_AGNOSTIC = 'DISEASE_AGNOSTIC',
  GASTRO_KDNEY_LIVER = 'GASTRO_KDNEY_LIVER',
  INFECTION_INFLAMATION = 'INFECTION_INFLAMATION',
  MATERNITY_REPRODUCTIVE_HEALTH = 'MATERNITY_REPRODUCTIVE_HEALTH',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  NEUROLOGY = 'NEUROLOGY',
  POPULATION_HEALTH = 'POPULATION_HEALTH',
  RESPIRATORY = 'RESPIRATORY',
  UROLOGY = 'UROLOGY',
  WORKFORCE_AND_EDUCATION = 'WORKFORCE_AND_EDUCATION'
}

export enum InnovationCareSettingCatalogueEnum {
  STP_ICS = 'STP_ICS',
  CCGS = 'CCGS',
  ACUTE_TRUSTS_INPATIENT = 'ACUTE_TRUSTS_INPATIENT',
  ACUTE_TRUSTS_OUTPATIENT = 'ACUTE_TRUSTS_OUTPATIENT',
  PRIMARY_CARE = 'PRIMARY_CARE',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  AMBULANCE = 'AMBULANCE',
  SOCIAL_CARE = 'SOCIAL_CARE',
  INDUSTRY = 'INDUSTRY',
  COMMUNITY = 'COMMUNITY',
  ACADEMIA = 'ACADEMIA',
  DOMICILIARY_CARE = 'DOMICILIARY_CARE',
  PHARMACY = 'PHARMACY',
  URGENT_AND_EMERGENCY = 'URGENT_AND_EMERGENCY',
  OTHER = 'OTHER'
}

export enum InnovationRevenueTypeCatalogueEnum {
  ADVERTISING = 'ADVERTISING',
  DIRECT_PRODUCT_SALES = 'DIRECT_PRODUCT_SALES',
  FEE_FOR_SERVICE = 'FEE_FOR_SERVICE',
  LEASE = 'LEASE',
  SALES_OF_CONSUMABLES_OR_ACCESSORIES = 'SALES_OF_CONSUMABLES_OR_ACCESSORIES',
  SUBSCRIPTION = 'SUBSCRIPTION',
  OTHER = 'OTHER'
}

export enum InnovationCertificationCatalogueEnum {
  CE_UKCA_NON_MEDICAL = 'CE_UKCA_NON_MEDICAL',
  CE_UKCA_CLASS_I = 'CE_UKCA_CLASS_I',
  CE_UKCA_CLASS_II_A = 'CE_UKCA_CLASS_II_A',
  CE_UKCA_CLASS_II_B = 'CE_UKCA_CLASS_II_B',
  CE_UKCA_CLASS_III = 'CE_UKCA_CLASS_III',
  IVD_GENERAL = 'IVD_GENERAL',
  IVD_SELF_TEST = 'IVD_SELF_TEST',
  IVD_ANNEX_LIST_A = 'IVD_ANNEX_LIST_A',
  IVD_ANNEX_LIST_B = 'IVD_ANNEX_LIST_B',
  MARKETING = 'MARKETING',
  CQC = 'CQC',
  DTAC = 'DTAC',
  OTHER = 'OTHER'
}

export enum InnovationSupportTypeCatalogueEnum {
  ADOPTION = 'ADOPTION',
  ASSESSMENT = 'ASSESSMENT',
  PRODUCT_MIGRATION = 'PRODUCT_MIGRATION',
  CLINICAL_TESTS = 'CLINICAL_TESTS',
  COMMERCIAL = 'COMMERCIAL',
  PROCUREMENT = 'PROCUREMENT',
  DEVELOPMENT = 'DEVELOPMENT',
  EVIDENCE_EVALUATION = 'EVIDENCE_EVALUATION',
  FUNDING = 'FUNDING',
  INFORMATION = 'INFORMATION',
}

export enum MaturityLevelCatalogueEnum {
  DISCOVERY = 'DISCOVERY',
  ADVANCED = 'ADVANCED',
  READY = 'READY'
}

export enum GeneralBenefitCatalogueEnum {
  REDUCE_LENGTH_STAY = 'REDUCE_LENGTH_STAY',
  REDUCE_CRITICAL_CARE = 'REDUCE_CRITICAL_CARE',
  REDUCE_EMERGENCY_ADMISSIONS = 'REDUCE_EMERGENCY_ADMISSIONS',
  CHANGES_DELIVERY_SECONDARY_TO_PRIMARY = 'CHANGES_DELIVERY_SECONDARY_TO_PRIMARY',
  CHANGES_DELIVERY_INPATIENT_TO_DAY_CASE = 'CHANGES_DELIVERY_INPATIENT_TO_DAY_CASE',
  INCREASES_COMPLIANCE = 'INCREASES_COMPLIANCE',
  IMPROVES_COORDINATION = 'IMPROVES_COORDINATION',
  REDUCES_REFERRALS = 'REDUCES_REFERRALS',
  LESS_TIME = 'LESS_TIME',
  FEWER_STAFF = 'FEWER_STAFF',
  FEWER_APPOINTMENTS = 'FEWER_APPOINTMENTS',
  COST_SAVING = 'COST_SAVING',
  INCREASES_EFFICIENCY = 'INCREASES_EFFICIENCY',
  IMPROVES_PERFORMANCE = 'IMPROVES_PERFORMANCE',
  OTHER = 'OTHER'
}

export enum EnvironmentalBenefitCatalogueEnum {
  NO_SIGNIFICANT_BENEFITS = 'NO_SIGNIFICANT_BENEFITS',
  LESS_ENERGY = 'LESS_ENERGY',
  LESS_RAW_MATERIALS = 'LESS_RAW_MATERIALS',
  REDUCES_GAS_EMISSIONS = 'REDUCES_GAS_EMISSIONS',
  REDUCES_PLASTICS_USE = 'REDUCES_PLASTICS_USE',
  MINIMISES_WASTE = 'MINIMISES_WASTE',
  LOWER_ENVIRONMENTAL_IMPACT = 'LOWER_ENVIRONMENTAL_IMPACT',
  OPTIMIZES_FINITE_RESOURCE_USE = 'OPTIMIZES_FINITE_RESOURCE_USE',
  USES_RECYCLED_MATERIALS = 'USES_RECYCLED_MATERIALS',
  OTHER = 'OTHER'
}

export enum SubgroupBenefitCatalogueEnum {
  REDUCE_MORTALITY = 'REDUCE_MORTALITY',
  REDUCE_FURTHER_TREATMENT = 'REDUCE_FURTHER_TREATMENT',
  REDUCE_ADVERSE_EVENTS = 'REDUCE_ADVERSE_EVENTS',
  ENABLE_EARLIER_DIAGNOSIS = 'ENABLE_EARLIER_DIAGNOSIS',
  REDUCE_RISKS = 'REDUCE_RISKS',
  PREVENTS_CONDITION_OCCURRING = 'PREVENTS_CONDITION_OCCURRING',
  AVOIDS_UNNECESSARY_TREATMENT = 'AVOIDS_UNNECESSARY_TREATMENT',
  ENABLES_NON_INVASIVELY_TEST = 'ENABLES_NON_INVASIVELY_TEST',
  INCREASES_SELF_MANAGEMENT = 'INCREASES_SELF_MANAGEMENT',
  INCREASES_LIFE_QUALITY = 'INCREASES_LIFE_QUALITY',
  ENABLES_SHARED_CARE = 'ENABLES_SHARED_CARE',
  OTHER = 'OTHER'
}

export enum InnovationDiseaseConditionCatalogueEnum {
  BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_ALLERGIES = 'BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_ALLERGIES',
  BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_ANAPHYLAXIS = 'BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_ANAPHYLAXIS',
  BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_BLOOD_CONDITIONS = 'BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_BLOOD_CONDITIONS',
  BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_LYMPHOEDEMA = 'BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_LYMPHOEDEMA',
  BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_SYSTEMIC_LUPUS_ERYTHEMATOSUS = 'BLOOD_AND_IMMUNE_SYSTEM_CONDITIONS_SYSTEMIC_LUPUS_ERYTHEMATOSUS',
  CANCER_BLADDER_CANCER = 'CANCER_BLADDER_CANCER',
  CANCER_BLOOD_AND_BONE_MARROW_CANCERS = 'CANCER_BLOOD_AND_BONE_MARROW_CANCERS',
  CANCER_BRAIN_CANCERS = 'CANCER_BRAIN_CANCERS',
  CANCER_BREAST_CANCER = 'CANCER_BREAST_CANCER',
  CANCER_CERVICAL_CANCER = 'CANCER_CERVICAL_CANCER',
  CANCER_COLORECTAL_CANCER = 'CANCER_COLORECTAL_CANCER',
  CANCER_COMPLICATIONS_OF_CANCER = 'CANCER_COMPLICATIONS_OF_CANCER',
  CANCER_ENDOMETRIAL_CANCERS = 'CANCER_ENDOMETRIAL_CANCERS',
  CANCER_HEAD_AND_NECK_CANCERS = 'CANCER_HEAD_AND_NECK_CANCERS',
  CANCER_LIVER_CANCERS = 'CANCER_LIVER_CANCERS',
  CANCER_LUNG_CANCER = 'CANCER_LUNG_CANCER',
  CANCER_METASTASES = 'CANCER_METASTASES',
  CANCER_OESOPHAGEAL_CANCER = 'CANCER_OESOPHAGEAL_CANCER',
  CANCER_OVARIAN_CANCER = 'CANCER_OVARIAN_CANCER',
  CANCER_PANCREATIC_CANCER = 'CANCER_PANCREATIC_CANCER',
  CANCER_PENILE_AND_TESTICULAR_CANCER = 'CANCER_PENILE_AND_TESTICULAR_CANCER',
  CANCER_PERITONEAL_CANCER = 'CANCER_PERITONEAL_CANCER',
  CANCER_PROSTATE_CANCER = 'CANCER_PROSTATE_CANCER',
  CANCER_RENAL_CANCER = 'CANCER_RENAL_CANCER',
  CANCER_SARCOMA = 'CANCER_SARCOMA',
  CANCER_SKIN_CANCER = 'CANCER_SKIN_CANCER',
  CANCER_STOMACH_CANCER = 'CANCER_STOMACH_CANCER',
  CANCER_THYROID_CANCER = 'CANCER_THYROID_CANCER',
  CANCER_UPPER_AIRWAYS_TRACT_CANCERS = 'CANCER_UPPER_AIRWAYS_TRACT_CANCERS',
  CARDIOVASCULAR_CONDITIONS_ACUTE_CORONARY_SYNDROMES = 'CARDIOVASCULAR_CONDITIONS_ACUTE_CORONARY_SYNDROMES',
  CARDIOVASCULAR_CONDITIONS_AORTIC_ANEURYSMS = 'CARDIOVASCULAR_CONDITIONS_AORTIC_ANEURYSMS',
  CARDIOVASCULAR_CONDITIONS_CRANIAL_ANEURYSMS = 'CARDIOVASCULAR_CONDITIONS_CRANIAL_ANEURYSMS',
  CARDIOVASCULAR_CONDITIONS_EMBOLISM_AND_THROMBOSIS = 'CARDIOVASCULAR_CONDITIONS_EMBOLISM_AND_THROMBOSIS',
  CARDIOVASCULAR_CONDITIONS_HEART_FAILURE = 'CARDIOVASCULAR_CONDITIONS_HEART_FAILURE',
  CARDIOVASCULAR_CONDITIONS_HEART_RHYTHM_CONDITIONS = 'CARDIOVASCULAR_CONDITIONS_HEART_RHYTHM_CONDITIONS',
  CARDIOVASCULAR_CONDITIONS_HYPERTENSION = 'CARDIOVASCULAR_CONDITIONS_HYPERTENSION',
  CARDIOVASCULAR_CONDITIONS_PERIPHERAL_CIRCULATORY_CONDITIONS = 'CARDIOVASCULAR_CONDITIONS_PERIPHERAL_CIRCULATORY_CONDITIONS',
  CARDIOVASCULAR_CONDITIONS_STABLE_ANGINA = 'CARDIOVASCULAR_CONDITIONS_STABLE_ANGINA',
  CARDIOVASCULAR_CONDITIONS_STROKE_AND_TRANSIENT_ISCHAEMIC_ATTACK = 'CARDIOVASCULAR_CONDITIONS_STROKE_AND_TRANSIENT_ISCHAEMIC_ATTACK',
  CARDIOVASCULAR_CONDITIONS_STRUCTURAL_HEART_DEFECTS = 'CARDIOVASCULAR_CONDITIONS_STRUCTURAL_HEART_DEFECTS',
  CARDIOVASCULAR_CONDITIONS_VARICOSE_VEINS = 'CARDIOVASCULAR_CONDITIONS_VARICOSE_VEINS',
  CHRONIC_AND_NEUROPATHIC_PAIN = 'CHRONIC_AND_NEUROPATHIC_PAIN',
  CHRONIC_FATIGUE_SYNDROME = 'CHRONIC_FATIGUE_SYNDROME',
  CYSTIC_FIBROSIS = 'CYSTIC_FIBROSIS',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_ADRENAL_DYSFUNCTION = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_ADRENAL_DYSFUNCTION',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_DIABETES = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_DIABETES',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_FAILURE_TO_THRIVE = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_FAILURE_TO_THRIVE',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_LIPID_DISORDERS = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_LIPID_DISORDERS',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_MALNUTRITION = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_MALNUTRITION',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_METABOLIC_CONDITIONS = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_METABOLIC_CONDITIONS',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_OBESITY = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_OBESITY',
  DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_THYROID_DISORDERS = 'DIABETES_AND_OTHER_ENDOCRINAL_NUTRITIONAL_AND_METABOLIC_CONDITIONS_THYROID_DISORDERS',
  DIGESTIVE_TRACT_CONDITIONS_CHOLELITHIASIS_AND_CHOLECYSTITIS = 'DIGESTIVE_TRACT_CONDITIONS_CHOLELITHIASIS_AND_CHOLECYSTITIS',
  DIGESTIVE_TRACT_CONDITIONS_COELIAC_DISEASE = 'DIGESTIVE_TRACT_CONDITIONS_COELIAC_DISEASE',
  DIGESTIVE_TRACT_CONDITIONS_CONSTIPATION = 'DIGESTIVE_TRACT_CONDITIONS_CONSTIPATION',
  DIGESTIVE_TRACT_CONDITIONS_DIARRHOEA_AND_VOMITING = 'DIGESTIVE_TRACT_CONDITIONS_DIARRHOEA_AND_VOMITING',
  DIGESTIVE_TRACT_CONDITIONS_DIVERTICULAR_DISEASE = 'DIGESTIVE_TRACT_CONDITIONS_DIVERTICULAR_DISEASE',
  DIGESTIVE_TRACT_CONDITIONS_FAECAL_INCONTINENCE = 'DIGESTIVE_TRACT_CONDITIONS_FAECAL_INCONTINENCE',
  DIGESTIVE_TRACT_CONDITIONS_GASTRO_OESOPHAGEAL_REFLUX_INCLUDING_BARRETTS_OESOPHAGUS = 'DIGESTIVE_TRACT_CONDITIONS_GASTRO_OESOPHAGEAL_REFLUX_INCLUDING_BARRETTS_OESOPHAGUS',
  DIGESTIVE_TRACT_CONDITIONS_GASTROPARESIS = 'DIGESTIVE_TRACT_CONDITIONS_GASTROPARESIS',
  DIGESTIVE_TRACT_CONDITIONS_HAEMORRHOIDS_AND_OTHER_ANAL_CONDITIONS = 'DIGESTIVE_TRACT_CONDITIONS_HAEMORRHOIDS_AND_OTHER_ANAL_CONDITIONS',
  DIGESTIVE_TRACT_CONDITIONS_HERNIA = 'DIGESTIVE_TRACT_CONDITIONS_HERNIA',
  DIGESTIVE_TRACT_CONDITIONS_INFLAMMATORY_BOWEL_DISEASE = 'DIGESTIVE_TRACT_CONDITIONS_INFLAMMATORY_BOWEL_DISEASE',
  DIGESTIVE_TRACT_CONDITIONS_IRRITABLE_BOWEL_SYNDROME = 'DIGESTIVE_TRACT_CONDITIONS_IRRITABLE_BOWEL_SYNDROME',
  DIGESTIVE_TRACT_CONDITIONS_LOWER_GASTROINTESTINAL_LESIONS = 'DIGESTIVE_TRACT_CONDITIONS_LOWER_GASTROINTESTINAL_LESIONS',
  DIGESTIVE_TRACT_CONDITIONS_PANCREATITIS = 'DIGESTIVE_TRACT_CONDITIONS_PANCREATITIS',
  DIGESTIVE_TRACT_CONDITIONS_UPPER_GASTROINTESTINAL_BLEEDING = 'DIGESTIVE_TRACT_CONDITIONS_UPPER_GASTROINTESTINAL_BLEEDING',
  EAR_NOSE_AND_THROAT_CONDITIONS = 'EAR_NOSE_AND_THROAT_CONDITIONS',
  EYE_CONDITIONS = 'EYE_CONDITIONS',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_CONTRACEPTION = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_CONTRACEPTION',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_FERTILITY = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_FERTILITY',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_INTRAPARTUM_CARE = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_INTRAPARTUM_CARE',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_POSTNATAL_CARE = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_POSTNATAL_CARE',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_PREGNANCY = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_PREGNANCY',
  FERTILITY_PREGNANCY_AND_CHILDBIRTH_TERMINATION_OF_PREGNANCY_SERVICES = 'FERTILITY_PREGNANCY_AND_CHILDBIRTH_TERMINATION_OF_PREGNANCY_SERVICES',
  GYNAECOLOGICAL_CONDITIONS_ENDOMETRIOSIS_AND_FIBROIDS = 'GYNAECOLOGICAL_CONDITIONS_ENDOMETRIOSIS_AND_FIBROIDS',
  GYNAECOLOGICAL_CONDITIONS_HEAVY_MENSTRUAL_BLEEDING = 'GYNAECOLOGICAL_CONDITIONS_HEAVY_MENSTRUAL_BLEEDING',
  GYNAECOLOGICAL_CONDITIONS_MENOPAUSE = 'GYNAECOLOGICAL_CONDITIONS_MENOPAUSE',
  GYNAECOLOGICAL_CONDITIONS_UTERINE_PROLAPSE = 'GYNAECOLOGICAL_CONDITIONS_UTERINE_PROLAPSE',
  GYNAECOLOGICAL_CONDITIONS_VAGINAL_CONDITIONS = 'GYNAECOLOGICAL_CONDITIONS_VAGINAL_CONDITIONS',
  INFECTIONS_ANTIMICROBIAL_STEWARDSHIP = 'INFECTIONS_ANTIMICROBIAL_STEWARDSHIP',
  INFECTIONS_BITES_AND_STINGS = 'INFECTIONS_BITES_AND_STINGS',
  INFECTIONS_COVID_19 = 'INFECTIONS_COVID_19',
  INFECTIONS_FEVERISH_ILLNESS = 'INFECTIONS_FEVERISH_ILLNESS',
  INFECTIONS_HEALTHCARE_ASSOCIATED_INFECTIONS = 'INFECTIONS_HEALTHCARE_ASSOCIATED_INFECTIONS',
  INFECTIONS_HIV_AND_AIDS = 'INFECTIONS_HIV_AND_AIDS',
  INFECTIONS_INFLUENZA = 'INFECTIONS_INFLUENZA',
  INFECTIONS_MENINGITIS_AND_MENINGOCOCCAL_SEPTICAEMIA = 'INFECTIONS_MENINGITIS_AND_MENINGOCOCCAL_SEPTICAEMIA',
  INFECTIONS_SEPSIS = 'INFECTIONS_SEPSIS',
  INFECTIONS_SKIN_INFECTIONS = 'INFECTIONS_SKIN_INFECTIONS',
  INFECTIONS_TUBERCULOSIS = 'INFECTIONS_TUBERCULOSIS',
  INJURIES_ACCIDENTS_AND_WOUNDS = 'INJURIES_ACCIDENTS_AND_WOUNDS',
  KIDNEY_CONDITIONS_ACUTE_KIDNEY_INJURY = 'KIDNEY_CONDITIONS_ACUTE_KIDNEY_INJURY',
  KIDNEY_CONDITIONS_CHRONIC_KIDNEY_DISEASE = 'KIDNEY_CONDITIONS_CHRONIC_KIDNEY_DISEASE',
  KIDNEY_CONDITIONS_RENAL_STONES = 'KIDNEY_CONDITIONS_RENAL_STONES',
  LIVER_CONDITIONS_CHRONIC_LIVER_DISEASE = 'LIVER_CONDITIONS_CHRONIC_LIVER_DISEASE',
  LIVER_CONDITIONS_HEPATITIS = 'LIVER_CONDITIONS_HEPATITIS',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ADDICTION = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ADDICTION',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ALCOHOL_USE_DISORDERS = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ALCOHOL_USE_DISORDERS',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ANXIETY = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ANXIETY',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ATTENTION_DEFICIT_DISORDER = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_ATTENTION_DEFICIT_DISORDER',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_AUTISM = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_AUTISM',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_BIPOLAR_DISORDER = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_BIPOLAR_DISORDER',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DELIRIUM = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DELIRIUM',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DEMENTIA = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DEMENTIA',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DEPRESSION = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DEPRESSION',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DRUG_MISUSE = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_DRUG_MISUSE',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_EATING_DISORDERS = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_EATING_DISORDERS',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_MENTAL_HEALTH_SERVICES = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_MENTAL_HEALTH_SERVICES',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_PERSONALITY_DISORDERS = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_PERSONALITY_DISORDERS',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_PSYCHOSIS_AND_SCHIZOPHRENIA = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_PSYCHOSIS_AND_SCHIZOPHRENIA',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_SELF_HARM = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_SELF_HARM',
  MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_SUICIDE_PREVENTION = 'MENTAL_HEALTH_AND_BEHAVIOURAL_CONDITIONS_SUICIDE_PREVENTION',
  MULTIPLE_LONG_TERM_CONDITIONS = 'MULTIPLE_LONG_TERM_CONDITIONS',
  MUSCULOSKELETAL_CONDITIONS_ARTHRITIS = 'MUSCULOSKELETAL_CONDITIONS_ARTHRITIS',
  MUSCULOSKELETAL_CONDITIONS_FRACTURES = 'MUSCULOSKELETAL_CONDITIONS_FRACTURES',
  MUSCULOSKELETAL_CONDITIONS_HIP_CONDITIONS = 'MUSCULOSKELETAL_CONDITIONS_HIP_CONDITIONS',
  MUSCULOSKELETAL_CONDITIONS_JOINT_REPLACEMENT = 'MUSCULOSKELETAL_CONDITIONS_JOINT_REPLACEMENT',
  MUSCULOSKELETAL_CONDITIONS_KNEE_CONDITIONS = 'MUSCULOSKELETAL_CONDITIONS_KNEE_CONDITIONS',
  MUSCULOSKELETAL_CONDITIONS_LOW_BACK_PAIN = 'MUSCULOSKELETAL_CONDITIONS_LOW_BACK_PAIN',
  MUSCULOSKELETAL_CONDITIONS_MAXILLOFACIAL_CONDITIONS = 'MUSCULOSKELETAL_CONDITIONS_MAXILLOFACIAL_CONDITIONS',
  MUSCULOSKELETAL_CONDITIONS_OSTEOPOROSIS = 'MUSCULOSKELETAL_CONDITIONS_OSTEOPOROSIS',
  MUSCULOSKELETAL_CONDITIONS_SPINAL_CONDITIONS = 'MUSCULOSKELETAL_CONDITIONS_SPINAL_CONDITIONS',
  NEUROLOGICAL_CONDITIONS_EPILEPSY = 'NEUROLOGICAL_CONDITIONS_EPILEPSY',
  NEUROLOGICAL_CONDITIONS_HEADACHES = 'NEUROLOGICAL_CONDITIONS_HEADACHES',
  NEUROLOGICAL_CONDITIONS_METASTATIC_SPINAL_CORD_COMPRESSION = 'NEUROLOGICAL_CONDITIONS_METASTATIC_SPINAL_CORD_COMPRESSION',
  NEUROLOGICAL_CONDITIONS_MOTOR_NEURONE_DISEASE = 'NEUROLOGICAL_CONDITIONS_MOTOR_NEURONE_DISEASE',
  NEUROLOGICAL_CONDITIONS_MULTIPLE_SCLEROSIS = 'NEUROLOGICAL_CONDITIONS_MULTIPLE_SCLEROSIS',
  NEUROLOGICAL_CONDITIONS_PARKINSONS_DISEASE_TREMOR_AND_DYSTONIA = 'NEUROLOGICAL_CONDITIONS_PARKINSONS_DISEASE_TREMOR_AND_DYSTONIA',
  NEUROLOGICAL_CONDITIONS_SPASTICITY = 'NEUROLOGICAL_CONDITIONS_SPASTICITY',
  NEUROLOGICAL_CONDITIONS_TRANSIENT_LOSS_OF_CONSCIOUSNESS = 'NEUROLOGICAL_CONDITIONS_TRANSIENT_LOSS_OF_CONSCIOUSNESS',
  ORAL_AND_DENTAL_HEALTH = 'ORAL_AND_DENTAL_HEALTH',
  RESPIRATORY_CONDITIONS_ASTHMA = 'RESPIRATORY_CONDITIONS_ASTHMA',
  RESPIRATORY_CONDITIONS_CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE = 'RESPIRATORY_CONDITIONS_CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE',
  RESPIRATORY_CONDITIONS_CYSTIC_FIBROSIS = 'RESPIRATORY_CONDITIONS_CYSTIC_FIBROSIS',
  RESPIRATORY_CONDITIONS_MESOTHELIOMA = 'RESPIRATORY_CONDITIONS_MESOTHELIOMA',
  RESPIRATORY_CONDITIONS_PNEUMONIA = 'RESPIRATORY_CONDITIONS_PNEUMONIA',
  RESPIRATORY_CONDITIONS_PULMONARY_FIBROSIS = 'RESPIRATORY_CONDITIONS_PULMONARY_FIBROSIS',
  RESPIRATORY_CONDITIONS_RESPIRATORY_INFECTIONS = 'RESPIRATORY_CONDITIONS_RESPIRATORY_INFECTIONS',
  SKIN_CONDITIONS_ACNE = 'SKIN_CONDITIONS_ACNE',
  SKIN_CONDITIONS_DIABETIC_FOOT = 'SKIN_CONDITIONS_DIABETIC_FOOT',
  SKIN_CONDITIONS_ECZEMA = 'SKIN_CONDITIONS_ECZEMA',
  SKIN_CONDITIONS_PRESSURE_ULCERS = 'SKIN_CONDITIONS_PRESSURE_ULCERS',
  SKIN_CONDITIONS_PSORIASIS = 'SKIN_CONDITIONS_PSORIASIS',
  SKIN_CONDITIONS_WOUND_MANAGEMENT = 'SKIN_CONDITIONS_WOUND_MANAGEMENT',
  SLEEP_AND_SLEEP_CONDITIONS = 'SLEEP_AND_SLEEP_CONDITIONS',
  UROLOGICAL_CONDITIONS_LOWER_URINARY_TRACT_SYMPTOMS = 'UROLOGICAL_CONDITIONS_LOWER_URINARY_TRACT_SYMPTOMS',
  UROLOGICAL_CONDITIONS_URINARY_INCONTINENCE = 'UROLOGICAL_CONDITIONS_URINARY_INCONTINENCE',
  UROLOGICAL_CONDITIONS_URINARY_TRACT_INFECTION = 'UROLOGICAL_CONDITIONS_URINARY_TRACT_INFECTION'
}
