export enum NotifierTypeEnum {
  INNOVATOR_ACCOUNT_CREATION = 'INNOVATOR_ACCOUNT_CREATION',
  INNOVATION_SUBMITED = 'INNOVATION_SUBMITED',
  NEEDS_ASSESSMENT_STARTED = 'NEEDS_ASSESSMENT_STARTED',
  NEEDS_ASSESSMENT_COMPLETED = 'NEEDS_ASSESSMENT_COMPLETED',
  NEEDS_ASSESSMENT_ASSESSOR_UPDATE = 'NEEDS_ASSESSMENT_ASSESSOR_UPDATE',
  INNOVATION_SUPPORT_STATUS_UPDATE = 'INNOVATION_SUPPORT_STATUS_UPDATE',
  INNOVATION_ORGANISATION_UNITS_SUGGESTION = 'INNOVATION_ORGANISATION_UNITS_SUGGESTION',
  ACTION_CREATION = 'ACTION_CREATION',
  ACTION_UPDATE = 'ACTION_UPDATE',

  THREAD_CREATION = 'THREAD_CREATION',
  THREAD_MESSAGE_CREATION = 'THREAD_MESSAGE_CREATION',
  INNOVATION_WITHDRAWN = 'INNOVATION_WITHDRAWN',
  INNOVATION_TRANSFER_OWNERSHIP_CREATION = 'INNOVATION_TRANSFER_OWNERSHIP_CREATION',
  INNOVATION_TRANSFER_OWNERSHIP_COMPLETED = 'INNOVATION_TRANSFER_OWNERSHIP_COMPLETED',
  INNOVATION_RECORD_EXPORT_REQUEST = 'INNOVATION_RECORD_EXPORT_REQUEST',
  INNOVATION_RECORD_EXPORT_FEEDBACK = 'INNOVATION_RECORD_EXPORT_FEEDBACK',
  INNOVATION_SUPPORT_STATUS_CHANGE_REQUEST = 'INNOVATION_SUPPORT_STATUS_CHANGE_REQUEST',
  INNOVATION_STOP_SHARING = 'INNOVATION_STOP_SHARING',
  INNOVATION_REASSESSMENT_REQUEST = 'INNOVATION_REASSESSMENT_REQUEST',
  INNOVATION_COLLABORATOR_INVITE = 'INNOVATION_COLLABORATOR_INVITE', 
  INNOVATION_COLLABORATOR_UPDATE = 'INNOVATION_COLLABORATOR_UPDATE',
  
  // Admin module.
  SLS_VALIDATION = 'SLS_VALIDATION',
  LOCK_USER = 'LOCK_USER',
  ACCESSOR_UNIT_CHANGE = 'ACCESSOR_UNIT_CHANGE',
  UNIT_INACTIVATION_SUPPORT_COMPLETED = 'UNIT_INACTIVATION_SUPPORT_COMPLETED',

  // Recurrent notifications.
  DAILY_DIGEST = 'DAILY_DIGEST',
  INCOMPLETE_INNOVATION_RECORD = 'INCOMPLETE_INNOVATION_RECORD',
  IDLE_SUPPORT = 'IDLE_SUPPORT',
}
