export enum ServiceRoleEnum {
  ADMIN = 'ADMIN',
  INNOVATOR = 'INNOVATOR',
  ACCESSOR = 'ACCESSOR',
  ASSESSMENT = 'ASSESSMENT',
  QUALIFYING_ACCESSOR = 'QUALIFYING_ACCESSOR',
}


export enum PhoneUserPreferenceEnum {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  DAILY = 'DAILY'
}
