export enum UserStatisticsEnum {
  WAITING_ASSESSMENT_COUNTER = 'WAITING_ASSESSMENT_COUNTER',
  ASSIGNED_INNOVATIONS_COUNTER = 'ASSIGNED_INNOVATIONS_COUNTER',
  INNOVATIONS_ASSIGNED_TO_ME_COUNTER = 'INNOVATIONS_ASSIGNED_TO_ME_COUNTER',
  TASKS_RESPONDED_COUNTER = 'TASKS_RESPONDED_COUNTER',
  INNOVATIONS_TO_REVIEW_COUNTER = 'INNOVATIONS_TO_REVIEW_COUNTER'
}
