export enum UserStatisticsEnum {
  WAITING_ASSESSMENT = 'WAITING_ASSESSMENT',
  ASSIGNED_INNOVATIONS = 'ASSIGNED_INNOVATIONS',
  INNOVATIONS_ASSIGNED_TO_ME = 'INNOVATIONS_ASSIGNED_TO_ME',
  ACTIONS_TO_REVIEW = 'ACTIONS_TO_REVIEW',
  INNOVATIONS_TO_REVIEW = 'INNOVATIONS_TO_REVIEW',
}
