export enum UserStatisticsEnum {
  WAITING_ASSESSMENT_COUNTER = 'WAITING_ASSESSMENT_COUNTER',
  INNOVATIONS_ASSIGNED_TO_ME_COUNTER = 'INNOVATIONS_ASSIGNED_TO_ME_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  INNOVATIONS_TO_REVIEW_COUNTER = 'INNOVATIONS_TO_REVIEW_COUNTER',
}
